### ISSUE TITLE
Fix small light grey headings to make it more readable

### ISSUE THREAD

**Issue by vjawahar** [fuseumass/hackumass.github.io#110]
- Occurrences: FAQ title, "Did we miss something?", "This hackathon is brought to you by..."
- Possible fixes: bold, highlight background, talk to PR/marketing about best design

**Comment by vjawahar** [comment]
From Jasmine: yellow text is hard to see on the white bg, add a "highlight" (the grey i use is #545454 hex) behind it OR boxes (to segment off different types of information) -- good example of this is the box that separates "Want to sponsor HackUMass?" at the end

**Comment by Anuj-Rathore24** [comment]
!assign
