### ISSUE TITLE
Travel Reimbursements in FAQ section

### ISSUE THREAD

**Issue by vjawahar** [fuseumass/hackumass.github.io#139]
- No travel reimbursements for this year's hackathon

**Comment by Shoximus** [comment]
Removed travel reimbursements from the index.html file. 

<img width="1109" alt="Screen Shot 2022-10-25 at 9 05 52 PM" src="https://user-images.githubusercontent.com/95514844/197911332-4b33b0bc-f437-47d7-9310-dab6213850bd.png">

<img width="1071" alt="Screen Shot 2022-10-25 at 9 06 12 PM" src="https://user-images.githubusercontent.com/95514844/197911363-920a6d77-c91c-4356-b9a6-0ded1ce48387.png">
