### ISSUE TITLE
Add tiktok's icon

### ISSUE THREAD

**Issue by ntdkhiem** [fuseumass/hackumass.github.io#181]
<img width="340" alt="image" src="https://github.com/fuseumass/hackumass.github.io/assets/25674728/d75942d3-4f6e-40c5-b315-2a7b543a8080">

Add the icon here.

**Comment by AVS1508** [comment]
Look into this way of integrating FontAwesome icons: [FontAwesome's Host Yourself - Web Fonts](https://fontawesome.com/v6/docs/web/setup/host-yourself/webfonts)
