### ISSUE TITLE
Update schedule.html to be consistent with HackUMass IX

### ISSUE THREAD

**Issue by AVS1508** [fuseumass/hackumass.github.io#53]
### Current View
![screencapture-hackumass-schedule-2021-10-16-13_35_35](https://user-images.githubusercontent.com/20084950/137597177-c103d50a-a538-4a7e-8a8f-98eb74d62de6.png)
**Check here: https://hackumass.com/schedule** (corresponding HTML file: `./schedule.html`)

### Desirable Changes
- Change the logo color (+ any primary color text) to Cornflower Blue (#7494EA)
- Update the website title and assets (favicon, etc.)
- Check the validity of `./assets/js/schedule.js` and modify accordingly

Feel free to add any other changes you feel are relevant!

**Comment by AlanBlandon** [comment]
:wave: Hello @AVS1508 may I work on this issue and issue #52?
