### ISSUE TITLE
Update "our team" section.

### ISSUE THREAD

**Issue by vjawahar** [fuseumass/hackumass.github.io#86]
- Remove carousel feature for team members.
- Update team members to reflect current team. 
- Gather team data (name, picture, position).
- Display team nicely at the bottom without the carousel.

**Comment by AVS1508** [comment]
Remove the 'our team' section for now, until we can gather the team data.

**Comment by Gazi10** [comment]
@AVS1508  When will the team data be available?

**Comment by Shoximus** [comment]
I have reached out to Annette for team info.

**Comment by Gazi10** [comment]
I did that. I got the infos of the directors only. Annette suggested to create a google form for other members to submit their infos. I'll get the form out by tonight.
